server:
  port: 7001
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false  #是否要注册到eureka
    fetch-registry: false  #表示是否从Eureka Server获取注册信息
    serviceUrl:   #服务端的地址
          defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/ #单机配置