server:
  port: 8001
  tomcat:
    uri-encoding: UTF-8
spring:
  application:
    name: STAR-LOGIN #我注册的这个服务叫什么名字
  datasource:
    url: jdbc:mysql://localhost:3306/sb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
      view:
        suffix: .jsp
        prefix: /WEB-INF/views/
  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true
  messages:
    encoding: UTF-8

eureka:
  client:
    service-url:
     defaultZone: http://localhost:7001/eureka  #服务注册的注册中心的地址

#mybatis的别名的配置
mybatis:
  type-aliases-package: com.cb.legou.domain
