server:
  port: 9527
spring:
  application:
    name: MICROSERVICE-ZUUL-GATEWAY #这个就是显示给他起个名字
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527 #显示的名字而已
    prefer-ip-address: true  #这个就是在页面的左下角显示他的访问的地址
zuul:
  routes:
    cb.serviceId: star-provider
    cb.path: /cb/** #路由映射：/cb/**这个路径的访问都路由到serverId服务处理

  prefix: "/legou"
  ignored-services: star-provider
